let levels =
  [
    {
      "levelnumber": 1,
      "isWon": false,
      "currentLevel": true,
      "movesStar": 2,
      "msStar": 3000,
      "stars": 0,
      "h": 5,
      "v": 5,
      "leveldata": ["E", "E", "E", "E", "E", "E", "E", "E", "R", "E", "E", "F", "E", "E", "E", "E", "E", "E", "P",
        "E", "R", "E", "E", "E", "E"]
    },
    {
      "levelnumber": 2,
      "isWon": false,
      "currentLevel": false,
      "movesStar": 5,
      "msStar": 5000,
      "stars": 0,
      "h": 7,
      "v": 7,
      "leveldata": ["F", "E", "R", "E", "E", "E", "E", "E", "E", "E", "E", "R", "E", "E", "E", "R", "E", "E", "E",
        "E", "E", "R", "E", "E", "R", "E", "E", "R", "E", "R", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "R",
        "E", "R", "E", "E", "E", "E", "E", "P"],
    },
    {
      "levelnumber": 3,
      "isWon": false,
      "currentLevel": false,
      "movesStar": 4,
      "msStar": 6000,
      "stars": 0,
      "h": 9,
      "v": 9,
      "leveldata": ["E", "R", "E", "E", "E", "E", "E", "E", "R", "E", "P", "E", "E", "R", "E", "E", "E", "E", "E",
        "E", "R", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "F", "E", "E", "E", "E", "E", "E",
        "E", "E", "E", "E", "E", "E", "E", "R", "E", "E", "E", "E", "R", "E", "E", "E", "E", "E", "R", "E", "E", "E",
        "R", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "R", "E", "E"]
    },
    {
      "levelnumber": 4,
      "isWon": false,
      "currentLevel": false,
      "movesStar": 10,
      "msStar": 15000,
      "stars": 0,
      "h": 11,
      "v": 11,
      "leveldata": ["E", "E", "E", "E", "E", "E", "R", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E",
        "E", "R", "E", "E", "R", "E", "E", "E", "E", "E", "E", "R", "E", "E", "E", "E", "E", "E", "E", "R", "E", "E",
        "E", "E", "E", "E", "E", "E", "E", "E", "E", "R", "R", "E", "E", "R", "R", "E", "E", "E", "E", "E", "P", "E",
        "R", "E", "R", "E", "R", "E", "E", "E", "E", "E", "R", "E", "E", "E", "E", "E", "R", "E", "E", "E", "R", "E",
        "E", "R", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "R", "E", "E", "E", "E", "E", "E", "R", "E", "E",
        "R", "R", "E", "E", "E", "E", "E", "E", "E", "R", "E", "E", "R", "F"]
    },
    {
      "levelnumber": 5,
      "isWon": false,
      "currentLevel": false,
      "movesStar": 5,
      "msStar": 12000,
      "stars": 0,
      "h": 12,
      "v": 12,
      "leveldata": ["E", "E", "E", "E", "E", "R", "E", "E", "E", "E", "E", "R", "E", "R", "E", "E", "E", "E", "R",
        "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "P", "E",
        "E", "E", "E", "E", "R", "E", "E", "E", "E", "E", "E", "E", "E", "R", "E", "E", "E", "E", "R", "E", "E", "R",
        "E", "R", "E", "E", "E", "R", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E",
        "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "R", "E", "F", "R", "E",
        "E", "E", "E", "E", "R", "E", "E", "E", "R", "E", "R", "E", "E", "E", "R", "E", "E", "E", "E", "E", "E", "E",
        "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "R", "R"]
    },
  ]

export let levelsconstants = levels